### ISSUE TITLE
Deletion not found

### ISSUE THREAD

**Issue by GustawEriksson** [biothings/myvariant.info#101]
Hi myVariantInfo!

I am getting a 404 error code when I query the deletion chr9:g.136419598del where a single nucleotide is deleted. I have tried two different approaches but none has been of success:

http://myvariant.info/v1/variant/chr9:g.136419598_136419599del
http://myvariant.info/v1/variant/chr9:g.136419598del

Can you please explain what I am doing wrong here?

Thanks for your great work!

**Comment by kevinxin90** [comment]
@GustawEriksson You're doing right. The query syntax is correct. It's just MyVariant.info doesn't contain annotation data for every single variant. It aggregates annotation existing data from sources listed [here](https://myvariant.info/v1/metadata). If you do find that this variant is present in one of these resources but not in MyVariant, pls let us know and we will see what's going wrong in our data ingestion pipeline. Thanks.

**Comment by GustawEriksson** [comment]
Ah ok! Thanks for the help @kevinxin90 !
