### ISSUE TITLE
"Unknown" for ClinVar origin

### ISSUE THREAD

**Issue by leexgh** [biothings/myvariant.info#105]
Hi,

I found there are some variants that have an `unknown` in ClinVar origin. For example:
https://myvariant.info/v1/variant/chr17%3Ag.7577538C%3ET
In the ClinVar -> rcv ->
```
      {
        "accession": "RCV000235221",
        "clinical_significance": "Pathogenic",
        "conditions": {
          "identifiers": {
            "medgen": "CN517202"
          },
          "name": "not provided"
        },
        "last_evaluated": "2018-11-21",
        "number_submitters": 4,
        "origin": "unknown",
        "preferred_name": "NM_000546.6(TP53):c.743G>A (p.Arg248Gln)",
        "review_status": "criteria provided, multiple submitters, no conflicts"
      },
```
What does this `unknown` mean?

**Comment by kevinxin90** [comment]
Hi @leexgh 

I would refer you to the documentation from the source database ClinVar: https://www.ncbi.nlm.nih.gov/clinvar/docs/properties/. As they mentioned, if refers to `Variants that of unknown origin.`

Other values of the origin fields could be germline, de novo, somatic, inherited, ...

Hope it answers your question.


Thanks!

**Comment by leexgh** [comment]
@kevinxin90 Thanks for your prompt reply, that helps!
