### ISSUE TITLE
myvariant::getVariants with rsIDs fail

### ISSUE THREAD

**Issue by sigven** [biothings/myvariant.info#133]
Hi,

I have successfully used your service (with the [myvariant R package](https://bioconductor.org/packages/release/bioc/html/myvariant.html)) to retrieve information on rsID's for a long time now. I feed the `getVariants` function with a relatively large list of rsIDs and `field = "dbsnp"`, which will then return basic information on these variants. I am now however experiencing error codes from this function (or the underlying API).

`> rs_list`
`[1] "rs10474608" "rs1047781"  "rs10479013" "rs10479542" "rs1048169"  "rs1048374" `
`> myvariant::getVariants(rs_list, fields="dbsnp")`

Error in .request.post(myvariant = myvariant, path, params = params.i) : 
  Request returned unexpected status code:
Response [http://myvariant.info/v1/variant/]
  Date: 2021-08-24 11:30
  Status: 400
  Content-Type: application/json; charset=UTF-8
  Size: 54 B

Occassionaly, some queries return with success it seems, but most of them return errors. Any idea what I am doing wrong, or if I need to change my query somehow?

regards,
Sigve

**Comment by erikyao** [comment]
Hi @sigven, thank you for using our service. We will look into this issue and keep you updated.

**Comment by namespacestd0** [comment]
We have pushed a server update to resolve the issue. Please verify.

**Comment by sigven** [comment]
Just re-ran my queries now, and they work fine (as before). Thanks for the rapid feedback and quick fix, highly appreciated! Closing the issue.
