### ISSUE TITLE
Use pre-compiled regex to accelerate matching

### ISSUE THREAD

**Issue by erikyao** [biothings/myvariant.info#139]
[src/utils/hgvs.py](https://github.com/biothings/myvariant.info/blob/master/src/utils/hgvs.py) uses `re` module a lot. If we compile the regex patterns in advance, it will save a lot of time when parsing the documents where this `hgvs.py` is used. 

I have made a minimal working example (in jupyter notebook) here:

```python
# Generate a sample of random sequences

import random
random.seed(1002)

def random_seq(length):
    return ''.join(random.choice('CGTA') for _ in range(length))

seq_list = []  # 100 sequences in total 
for length in range(1, 11):
    seq_sublist = [random_seq(length) for _ in range(10)]
    seq_list += seq_sublist
```

```python
# Target functions: un-compiled vs compiled

def match_1(seq_list):
    for seq in seq_list:
        re.match('^[ACGTN]+$', seq)

SEQ_PATTERN = re.compile('^[ACGTN]+$')
def match_2(seq_list):
    for seq in seq_list:
        # re.match(SEQ_PATTERN, seq)  # actually slower than re.match('^[ACGTN]+$', seq)
        SEQ_PATTERN.match(seq)
```

```python
# Performance Comparison

%timeit -n 100 -r 100 match_1(seq_list)
86.9 µs ± 2.63 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)

%timeit -n 100 -r 100 match_2(seq_list)
35.4 µs ± 1.4 µs per loop (mean ± std. dev. of 100 runs, 100 loops each)
```

The compiled version is 60% faster than the un-compiled one.

This `^[ACGTN]+$` pattern is matched in the [`get_hgvs_from_vcf()` function](https://github.com/biothings/myvariant.info/blob/master/src/utils/hgvs.py#L92), which is further used by a few parsers. E.g. consider the _gnomad_ parser. We have 1,055,643,939 _gnomad_ documents. If each document matches the above pattern twice, we can reduce the matching time from 30 minutes to 12.

```python
# Time Elapsed

1055643939 * 2 / 100 * 86.9 / (10**6) / 60  # us to minute
30.5784860997

1055643939 * 2 / 100 * 35.4 / (10**6) / 60  # us to minute
12.4565984802
```

**Comment by erikyao** [comment]
Related Issue: https://github.com/biothings/myvariant.info/issues/116

**Comment by zcqian** [comment]
I wonder if it would actually be helpful. Python's `re` will compile and cache things automatically.

https://github.com/python/cpython/blob/f84e2f6c0aca97c59ec8ce21715ae9bd89893307/Lib/re.py#L187-L191

https://github.com/python/cpython/blob/f84e2f6c0aca97c59ec8ce21715ae9bd89893307/Lib/re.py#L288-L295

**Comment by erikyao** [comment]
@zcqian thanks for the information! I found I made a mistake building up the tests. Additionally, I found that `re.match(compiled_pattern, string)` is actually slower. We should switch to `compiled_pattern.match(string)` which saves the cache lookup overhead. Please find the updated results above.

**Comment by zcqian** [comment]
still a pretty significant speedup, nice.
