### ISSUE TITLE
How to get annotations for hg38 variants

### ISSUE THREAD

**Issue by bw2** [biothings/myvariant.info#174]
Thanks for maintaining this nice API. 
I'd like to retrieve annotations for hg38 variants like chr8-140300616-T-G	
I'm confused after reading the docs because the table under 
https://docs.myvariant.info/en/latest/doc/data.html#available-fields
shows many annotation available for hg38, but I don't see a way to specify a genome reference version for the /variant endpoint @
https://myvariant.info/v1/api#/variant/get_variant__id_

**Comment by erikyao** [comment]
Hi @bw2, thanks for reaching out.

We support `assembly=hg38` parameter to query on variants on hg38. It's kind of under-documented but you can check https://github.com/biothings/myvariant.info/issues/96.

Please let me know if I can be of any help.

**Comment by bw2** [comment]
That solves it, thanks.
