### ISSUE TITLE
index all `clinvar.rcv.conditions.identifiers` fields, including mondo and mesh

### ISSUE THREAD

**Issue by colleenXu** [biothings/myvariant.info#175]
The best way to address https://github.com/biothings/biothings_explorer/issues/548 is if BTE can use and query the `clinvar.rcv.conditions.identifiers.mondo` (example) and `clinvar.rcv.conditions.identifiers.mesh` fields. 

However, these fields don't seem to be indexed:
* they're not listed in the [metadata/fields](https://myvariant.info/v1/metadata/fields) response
* `_exists_` queries for those fields don't return any hits ([mondo](https://myvariant.info/v1/query?q=_exists_:clinvar.rcv.conditions.identifiers.mondo&fields=clinvar), [mesh](https://myvariant.info/v1/query?q=_exists_:clinvar.rcv.conditions.identifiers.mesh&fields=clinvar))
* no hits are returned when trying to query using those fields ([mondo](https://myvariant.info/v1/query?q=clinvar.rcv.conditions.identifiers.mondo:%22MONDO:0005105%22), [mesh](https://myvariant.info/v1/query?q=clinvar.rcv.conditions.identifiers.mesh:D008545))

So at minimum, it would help to have these two fields indexed. 

I'm not sure if there's more non-indexed fields for `clinvar.rcv.conditions.identifiers` data that I'm not aware of. If there are more, I'd like to kow what they are: they may also be useful to have indexed / used by BTE...

**Comment by everaldorodrigo** [comment]
The fields `mondo` and `mesh` are added to the mapping here: #181
