### ISSUE TITLE
Which config file?

### ISSUE THREAD

**Issue by joaquinvanschoren** [biothings/myvariant.info#23]
When installing myvariant and testing, it asks for a BioThings config file. Which file should we use or how should we configure it? Thanks.

**Comment by newgene** [comment]
I believe "myvariant standalone instance" is what you are looking for:

http://docs.biothings.io/en/latest/doc/standalone.html#myvariantlogo

MyVariant.info requires the underlying data to run locally. This standalone instance option is the supported way to set up your own MyVariant.info instance.

Will close this issue now, and let us if you need any further information.
