### ISSUE TITLE
evaluate denovo-db and add if appropriate

### ISSUE THREAD

**Issue by andrewsu** [biothings/myvariant.info#27]
https://academic.oup.com/nar/article/45/D1/D804/2770653/denovo-db-a-compendium-of-human-de-novo-variants
http://denovo-db.gs.washington.edu/denovo-db/Download.jsp
http://denovo-db.gs.washington.edu/denovo-db/Usage.jsp

from https://github.com/monarch-initiative/MDAC/issues/2

**Comment by newgene** [comment]
@jeonbr made a myvariant.info "data plugin" here: https://github.com/jeonbr/denovodb

**Comment by newgene** [comment]
denovodb data are now available at http://pending.biothings.io/denovodb.
