### ISSUE TITLE
add github link to front page of myvariant.info

### ISSUE THREAD

**Issue by andrewsu** [biothings/myvariant.info#32]
also applies to mygene and mychem...

**Comment by gtsueng** [comment]
Do you mean you would like the github link moved from the About page to the landing page, or that you would like an additional github link added to the navigation bar?

**Comment by andrewsu** [comment]
Not super passionate about where it goes, but yes, my suggestion was that the link should appear somewhere on the front page...  I think that would be useful since the primary audience is developers...
