### ISSUE TITLE
update wellderly data

### ISSUE THREAD

**Issue by andrewsu** [biothings/myvariant.info#33]
Just noticed that the data from http://myvariant.info/v1/variant/chr12:g.1299226A%3EG?fields=wellderly differs from what's available from https://genomics.scripps.edu/browser/#.  The allele/genotype frequencies are different, and they also separate out the illumina data from complete genomics.  

Looks like the VCFs are here: https://genomics.scripps.edu/browser/files/wellderly/vcf/

**Comment by newgene** [comment]
Just an update here. A new version of Wellderly dataset should be available soon, and all the allele freqs will be re-calculated. We will reload Wellderly data when they are ready.

**Comment by newgene** [comment]
We have now received the updated wellderly dataset. Will start to upload the wellderly data in MyVariant.info.

**Comment by erikyao** [comment]
P.S. Dr. Torkamani indicated that this batch of wellderly data are version 2. Last upload was renamed "wellderly_v1" in mongodb.
