### ISSUE TITLE
ExAC mapping

### ISSUE THREAD

**Issue by kevinxin90** [biothings/myvariant.info#35]
The mapping file for ExAC contains a small problem. The ac_hom field should be put in 'ac' rather than 'hom'. 
Potential solutions:

- change the mapping

- add an additional field called 'ac_hom' under 'hom'

**Comment by newgene** [comment]
Let's correct the mapping, no need to change the data structure.

**Comment by kevinxin90** [comment]
Mapping has been fixed f52c30a012945a21daa8345e14fb0041c082caf1
