### ISSUE TITLE
CIViC auto upload

### ISSUE THREAD

**Issue by kevinxin90** [biothings/myvariant.info#37]
CIViC is loaded through API query. Should trigger it every month.

**Comment by sirloon** [comment]
Note: currently in parser, should be extracted in a dumper

**Comment by sirloon** [comment]
mapping has changed, we take the one generated from the inspector and index everything except "lifecycle_actions" (index:"no")

**Comment by sirloon** [comment]
needs to review pmids and other fields to convert types as needed

**Comment by newgene** [comment]
implemented since release "20190209". CIVIC data now updated monthly.
