### ISSUE TITLE
Better format when using both always_list and allow_null options?

### ISSUE THREAD

**Issue by CristianoYL** [biothings/myvariant.info#43]
In the recent release, I noticed that there're some handy new features, including the `always_list` and `allow_null` option. But when they are used in combination, the result is probably not in the nicest format. Instead of returning an empty list `[]` when there's no data, it returns a list of a null object like so: `[null]`.

It will cause some confusion for the client side, since usually you would check if the returned list is empty, as opposed to checking each element in the list if they are empty.

A sample request to reproduce this error would be:
```
https://myvariant.info/v1/query?q=rs12131234&fields=dbsnp&always_list=dbsnp.gene&allow_null=dbsnp.gene
```

I'm wondering if it's possible to change this behaviour? Thanks.

**Comment by newgene** [comment]
fixed by @cyrus0824 at https://github.com/biothings/biothings.api/commit/475c41cfc7f0650eb315cefe853e7a0331098517
