### ISSUE TITLE
change example query

### ISSUE THREAD

**Issue by andrewsu** [biothings/myvariant.info#54]
In the "Query Examples" of the myvariant.info home page, we currently show http://myvariant.info/v1/variant/chr1:g.35367G>A for annotation retrieval.  But, that specific variant has a rather limited set of annotation sources.  I'd suggest choosing another variant that better highlights as many of the annotation resources as possible.

**Comment by newgene** [comment]
This is a better one:

http://myvariant.info/v1/variant/chr7:g.55241707G%3ET

@marcodarko for making the change.

**Comment by newgene** [comment]
This is another one with even more available data sources:

http://myvariant.info/v1/variant/chr9:g.107620835G%3EA

**Comment by marcodarko** [comment]
Updated!
