### ISSUE TITLE
dbSNP parser missing variants

### ISSUE THREAD

**Issue by kevinxin90** [biothings/myvariant.info#61]
User report variant "rs281865162" is missing in MyVariant.info. The problem comes from the dbSNP parser:
In https://github.com/biothings/myvariant.info/blob/master/src/hub/dataload/sources/dbsnp/dbsnp_vcf_parser.py#L60, we specifically remove all variants which are not single nucleotide deletion. Not sure if it is on purpose.
Need @newgene to confirm.

**Comment by inodb** [comment]
@kevinxin90 does this mean only dbSNP variants of these types are supported:

- SNP
- deletion of single nucleotide

Or are insertions supported as well?

Thank you!

**Comment by kevinxin90** [comment]
Yes. Insertion is supported for the current version, e.g. http://myvariant.info/v1/variant/rs772309997.

We have a delay in the new MyVariant.info release. When it's released, you should be able to access all variants documented in dbSNP.

**Comment by inodb** [comment]
Thanks a lot @kevinxin90 !

**Comment by kevinxin90** [comment]
Fixed in bd23526f8e72766db657bb48622ba5980465805d

**Comment by kevinxin90** [comment]
@inodb We just completed the new MyVariant.info release. And you should be able to access all those deletion/insertion variants now.
