### ISSUE TITLE
data source: PheWAS catalog

### ISSUE THREAD

**Issue by andrewsu** [biothings/myvariant.info#66]
https://phewascatalog.org/phewas

I think that should contain all the data in supp tables 3 and 8 in https://www.nature.com/articles/nbt.2749, but would be good to double check.

also, this is from an older 2013 paper.  After this is loaded, would be good to check with the Vanderbilt team (eg Lisa Bastarache) whether there are any other relevant large-scale data available...

**Comment by kevinxin90** [comment]
Phewas parser ready at: https://github.com/kevinxin90/phewas

**Comment by newgene** [comment]
PheWAS API now available at https://pending.biothings.io/phewas

**Comment by andrewsu** [comment]
Add some example queries to https://pending.biothings.io/phewas? (currently only showing `/metadata` and `/metadata/fields`.)  

Was expecting https://pending.biothings.io/phewas/query?q=rs2075650 and/or https://pending.biothings.io/phewas/query?q=dementia to work...

**Comment by sirloon** [comment]
@andrewsu fields need to be specified in the query: https://pending.biothings.io/phewas/query?q=phewas.associations.phenotype.name:dementia

**Comment by andrewsu** [comment]
cool, makes sense, thanks.  Underscores the need to add a few example queries I think...

**Comment by sirloon** [comment]
@andrewsu there's a random query generator that usually provices those examples, for some reason it doesn't work for phewas. Edit: actually it does, but I think sometimes where the query it generated isn't valid, it's discarded, and if all tries failed, we don't have any example. @marcodarko any idea how to improve that ?

Example query generation failed, only metadata available:
![image](https://user-images.githubusercontent.com/2883770/61088526-60e97500-a3ed-11e9-9a1f-afed61cfadae.png)

sometimes it works:
![image](https://user-images.githubusercontent.com/2883770/61088583-8d9d8c80-a3ed-11e9-9be7-616c3b3f6199.png)

**Comment by andrewsu** [comment]
going to reopen this ticket and assign to Marco just to keep the UI enhancement on our radar...

**Comment by marcodarko** [comment]
This latest change guarantees a set number of examples (currently 8) and removes undefined or invalid values.  If there's any new issues let me know! If the first run doesn't return enough queries it will run again in the background until that total is met.

**Comment by andrewsu** [comment]
Looks good!
