### ISSUE TITLE
Missing gnomAD data

### ISSUE THREAD

**Issue by leexgh** [biothings/myvariant.info#75]
Hi myVairiantInfo team,

Thanks for the great work! Recently I found a variant that is missing from your gnomAD data.

 BRCA1 E23Vfs*17 is a highly recurrent germline variant which is present in gnomAD (https://gnomad.broadinstitute.org/variant/17-41276044-ACT-A),

but not in myvariant.info:
http://myvariant.info/v1/variant/chr17:g.41276045_41276046delCT

Could you fix it please? Thank you!

Xiang

**Comment by kevinxin90** [comment]
@leexgh 
Hi Xiang,

We have this variant in MyVariant.info. You could access it by: http://myvariant.info/v1/variant/chr17:g.41276045_41276046del. We normally remove the deleted nucleotides when representing a variant in HGVS id.

**Comment by leexgh** [comment]
@kevinxin90 Thank you! Good to know that.

**Comment by newgene** [comment]
also FYI @leexgh, additional info about the hgvs ids we use in [MyVariant.info](http://myvariant.info):

http://docs.myvariant.info/en/latest/doc/data.html#id-field

and this `format_hgvs` helper available from [myvariant.py](https://pypi.org/project/myvariant/) Python client:

https://myvariant-py.readthedocs.io/en/latest/#myvariant.MyVariantInfo.format_hgvs

(input is vcf style chr, pos, ref, alt, and output the valid hgvs id for MyVariant.info)

**Comment by leexgh** [comment]
@newgene thanks, that helps a lot!
