### ISSUE TITLE
Can't query deletion/insertion variants

### ISSUE THREAD

**Issue by leexgh** [biothings/myvariant.info#78]
Hi myVariantInfo team,

Thanks for all the improvements. I got an error when I query the deletion/insertion variant `chrX:g.14112_14117delinsTG`.
https://myvariant.info/v1/variant/chrX%3Ag.14112_14117delinsTG

And also this variant: `chr13:g.28611219_28611221delinsGC`
https://myvariant.info/v1/variant/chr3%3Ag.28611219_28611221delinsGC

Could you tell me how to query those del/ins variants please? Thanks a lot!

**Comment by kevinxin90** [comment]
Regarding the second variant: chr13:g.28611219_28611221delinsGC. This is related to a known issue of our dbSNP parser #61 . (Basically, our parser missed all delins variants from dbSNP database). We have fixed the issue in our backend. And our next release of MyVariant.info will come up in early June. You should be able to access this variant then. 

Regarding the first variant, I couldn't find this variant in any existing databases. Do you get it from one of the MyVariant.info documentation? Maybe this variant doesn't exist anymore.

In addition, there're many different ways to query variants through MyVariant.info (depending on what your input looks like):

- You could do it using VCF way by specifying chrom, ref, alt and pos: http://myvariant.info/v1/query?q=chrom:15%20AND%20vcf.alt:G%20AND%20vcf.position:91044589%20AND%20vcf.ref:GC

- You could also use rsid (dbsnp id): http://myvariant.info/v1/variant/rs1312532713

**Comment by leexgh** [comment]
@kevinxin90 Yes I find the first variant on MyVariant.info documentation. Thanks for your explanation!

**Comment by inodb** [comment]
Thanks @kevinxin90! do you support other input formats as well like MAF or VEP region? Thanks!

**Comment by kevinxin90** [comment]
For VEP region, you are referring to this type of format (e.g. 5:140532-140532:1/C), right?
Both are currently not supported. I don't expect it to be supported in the MyVariant.info API. But they would be helpful features to add in our Python client.

For example, currently, we have support to transform from VCF format to hgvs id in our python client (https://github.com/biothings/biothings_client.py/blob/faff290883c54128aeea47c75acc7e933c31cfb4/biothings_client/mixins/variant.py). We could add additional support to transform from MAF/VEP region to hgvs as well.

**Comment by inodb** [comment]
Thanks @kevinxin90 	!

**Comment by kevinxin90** [comment]
This issue is fixed now @leexgh. See example: http://myvariant.info/v1/variant/chr7:g.55242467_55242478delinsCAC

**Comment by leexgh** [comment]
@kevinxin90 great! thanks for letting me know
