### ISSUE TITLE
Novel variant details?

### ISSUE THREAD

**Issue by andyb3** [biothings/myvariant.info#80]
Hi,

Thanks for making this great tool!

Am I correct in thinking that MyVariant won't return any information for novel variants (i.e. not in any databases)?

For example I can't seem to pull out any information for the following b38 variant chr10:g.87933041_87933042insGTTA

```
mv = myvariant.MyVariantInfo()
v = mv.getvariants([mv.format_hgvs("10", "87933041", "C", "CGTTA")], assembly='hg38')
v[0]
{'query': 'chr10:g.87933041_87933042insGTTA', 'notfound': True}
```

I was wondering if there was a way to pull out basic information such as build 37 and build 38 coordinates, gene symbols, transcripts, HGVS etc. for novel variants?

Many thanks,
Andy

**Comment by kevinxin90** [comment]
Hi Andy,

Yes, you're right. MyVariant won't return info about novel variants.

There're actually a number of tools available which serve your purpose, e.g. SnpEff (we also use it to annotate all our variants) and ClinGen.

**Comment by andyb3** [comment]
Great thanks very much for your help!
