### ISSUE TITLE
Mongo data dump?

### ISSUE THREAD

**Issue by inodb** [biothings/myvariant.info#81]
Is there a data dump available for the entire Mongo database if one would want to run a local clone of myvariant.info? I guess there might be some restrictions for certain data licenses. Curious how big the current production database is. Thanks!

**Comment by sirloon** [comment]
We don't provide mongodb dumps, but rather ElasticSearch snapshots and diff files (full/incremental updates). If you want to run myvariant.info locally, have a look at this: http://docs.biothings.io/en/latest/doc/standalone.html, let me know if you want to go that way.

**Comment by inodb** [comment]
I see - thanks @sirloon ! That's v helpful!
