### ISSUE TITLE
support ClinGen's CAID in /v1/variant annotation endpoint

### ISSUE THREAD

**Issue by newgene** [biothings/myvariant.info#83]
We currently included ClinGen's CAID for variants on hg38 assembly, and it can be queried like this:

http://myvariant.info/v1/query?q=CA9996207&assembly=hg38

or 

http://myvariant.info/v1/query?q=clingen.caid:CA9996207&assembly=hg38

We should add `clingen.caid` to the supported ID types for [/v1/variant] (http://docs.myvariant.info/en/latest/doc/variant_annotation_service.html) annotation endpoint as well, so this should work as well:

http://myvariant.info/v1/variant/CA9996207?assembly=hg38

Once added, please update proper tests and documentation as well.

**Comment by namespacestd0** [comment]
Implemented in d10ecbcd100972acd9d149ac871cb8276d9e44fa. Need to add a test case.

**Comment by namespacestd0** [comment]
Test cases added in https://github.com/biothings/myvariant.info/commit/fac911d1f87cdc7089a2f601ff24c4b62284128b. Pending deployment.
