### ISSUE TITLE
Include variants with very long hgvs id (>512 chars)

### ISSUE THREAD

**Issue by newgene** [biothings/myvariant.info#91]
The `_id` field for a MyVariant.info variant object is typically an [HGVS id](http://docs.myvariant.info/en/latest/doc/data.html#id-field). Sometimes this hgvs id is very long (e.g. when a long insert sequence is included), which is beyond the limit of some database system we use (e.g. _id field for MongoDB should be <= 512 chars when sharding is used). Currently, these variants were skipped (just ~300 out of almost 1 billion variants in MyVariant.info).

This is a proposed solution to include these variants:

For a a long variant `_id` example like this one:
```
chr11:g.47342083_47342097delinsCTAAACCTCATCCTTCTCATCTCTAAAATGACGATGCTGAGGTGACCGCTCCAGAGGGTACTGAGAGGGTCATACGGGCCTGGTGAGCATCACCACCCCTCAGACACTTGAGGTTCCTTATGTGCACTGCACCATCACAGGCAAACATGGCACACACAGGCACACGTGTTTTCACATGCCCACATGCACCCAGACACGTGCGCACCAGCGCCCATGGGCCCACACGCCCTCCACAGGGATTCACGCCACACCCACACACCCTCCCGAGCTCAATGGCTCTGCCCTGCCCTGCAGAAAAGAAGCTGGAGGTGTACCAGAGCATCGCAGACCTGATGGTGGGCGCAAAGGACCAGCAGCCACAGTAGCTTGGCCTGGGGGAGCAGGGTGCGGGCGGTGGGGTGGCCGGGGCTGAGGGGTGGTGCTCAGCCTTTCAGAAGAAGCTGGAGCCGGCCTACCAGGTGAGCAAAGGCCACAAGATCCGGCTGACCGTGGAACTGGCTGACCATGACGCTGAGGTCAAATGGCTCAAGAATGGCCAGGAGATCCAGATGAGCGGCAGGTGCAGCCTGGGGTGGGGAGGGGGGCTCGGGTGGAGCAGCCACAGTAGCTTGGCCTGGGGGAGCAGGG
```
we will convert the long insertion sequence (after "delins") into a hashkey with this snippet:

```
from hashlib import blake2b
blake2b(x.encode('utf8'), digest_size=16).hexdigest()
```
where `x` is the long insertion sequence.

Then the `_id` become this:
```
chr11:g.47342083_47342097delins_SEQHASHED_78b0b513aa8eb34923b286a3f0ca701d
```
Note that we added a `_SEQHASHED_` prefix before the 32-char hash to serve as the easy signature for such a hashed id.

Then in the actual variant object, we will add a top-level field with the actual insertion sequence included:
```
{
  "_id": "chr11:g.47342083_47342097delins_SEQHASHED_78b0b513aa8eb34923b286a3f0ca701d",
  "_hashed_hgvs_id": {
    "78b0b513aa8eb34923b286a3f0ca701d": "CTAAACCTCATCCTTCTCATCTCTAAAATGACGATGCTGAGGTGACCGCTCCAGAGGGTACTGAGAGGGTCATACGGGCCTGGTGAGCATCACCACCCCTCAGACACTTGAGGTTCCTTATGTGCACTGCACCATCACAGGCAAACATGGCACACACAGGCACACGTGTTTTCACATGCCCACATGCACCCAGACACGTGCGCACCAGCGCCCATGGGCCCACACGCCCTCCACAGGGATTCACGCCACACCCACACACCCTCCCGAGCTCAATGGCTCTGCCCTGCCCTGCAGAAAAGAAGCTGGAGGTGTACCAGAGCATCGCAGACCTGATGGTGGGCGCAAAGGACCAGCAGCCACAGTAGCTTGGCCTGGGGGAGCAGGGTGCGGGCGGTGGGGTGGCCGGGGCTGAGGGGTGGTGCTCAGCCTTTCAGAAGAAGCTGGAGCCGGCCTACCAGGTGAGCAAAGGCCACAAGATCCGGCTGACCGTGGAACTGGCTGACCATGACGCTGAGGTCAAATGGCTCAAGAATGGCCAGGAGATCCAGATGAGCGGCAGGTGCAGCCTGGGGTGGGGAGGGGGGCTCGGGTGGAGCAGCCACAGTAGCTTGGCCTGGGGGAGCAGGG"
  }
}
```

A helper function `encode_long_hgvs_id(doc)` should be created in utils.hvgs module:

https://github.com/biothings/myvariant.info/blob/master/src/utils/hgvs.py

**Comment by sirloon** [comment]
I suggest not using the actual hash as the key in "_hashed_hgvs_id" dict as it will make the client code more complex if sequence is needed. Also, _hash_hgvs_id is confusing because it's not the whole HGVS ID that is hashed, only part of it.

We could have (to keep what's in _id)
```
"_SEQHASHED": {
   "hash" : "abcvcefgfde",
   "value": "CTAGCGGCGCGAGAG"
}
```

**Comment by newgene** [comment]
The above commit should resolve the issue. We should validate and document the variant objects with the above process (should be able to get the list of such variants with a query).

**Comment by erikyao** [comment]
To solve this problem completely, all uploaders in myvariant.info should use `EncodeLongHGVSIDStorage` or its subclasses. Currently there is only one uploader vulnerable:

- `class ClingenUploader(ParallelizedSourceUploader)`

Once tests pass on this class, problem is solved
