### ISSUE TITLE
gnomAD v3 available now

### ISSUE THREAD

**Issue by newgene** [biothings/myvariant.info#93]
gnomAD v3 was mapped to GRCh38.

https://macarthurlab.org/2019/10/16/gnomad-v3-0/

downloadable here:
https://gnomad.broadinstitute.org/downloads

However, the gnomAD team suggested gnomAD v2.1.1 is still recommended for most coding regions analyses:
https://gnomad.broadinstitute.org/faq#should-i-switch-to-the-latest-version-of-gnomad

So v3 should not replace current v2 data in MyVariant.info, but can be provided in parallel (e.g. in hg38 index only, or as a standalone API)

**Comment by cgpreston** [comment]
Thanks for this! -Christine Preston

**Comment by erikyao** [comment]
Please check the comments in [Issue#119: Revise the dbNSFP parser for release 4.2a](https://github.com/biothings/myvariant.info/issues/119#issuecomment-833016114)

We decided to discard the gnomAD fields in dbNSFP data. The gnomAD v3 data is to be updated individually.
