### ISSUE TITLE
Support hg38 on variant endpoint

### ISSUE THREAD

**Issue by leexgh** [biothings/myvariant.info#96]
Hi,

I'd like to query hg38 variants, is there a way I can query with `variant` endpoint? I found that the `query` endpoint supports hg38, like http://myvariant.info/v1/query?q=chr1:69000-70000&hg38=true, but on variant endpoint it doesn't work https://myvariant.info/v1/variant/chr7%3Ag.55181378C%3ET&hg38=true. Are you working on support hg38 for variant endpoint? How is the development status?

Thank you!

**Comment by newgene** [comment]
@leexgh both `query` and `variant` endpoints support `assembly=hg38` parameter to query on variants on hg38.

**Comment by leexgh** [comment]
@newgene thanks for your reply! Could you give me an example of how to query hg38 variants with `variant`? I tried with `chr7:g.55181378C>T`, but either `https://myvariant.info/v1/variant/chr7%3Ag.55181378C%3ET&hg38=true` or `https://myvariant.info/v1/variant/chr7%3Ag.55181378C%3ET&assembly=hg38` are not working

**Comment by kevinxin90** [comment]
@leexgh **assembly** is a **query parameter** in the url. So you should use **?** instead of **&**. E.g. https://myvariant.info/v1/variant/chr7:g.55181378C%3ET?assembly=hg38

**Comment by leexgh** [comment]
@kevinxin90 I see, that helps a lot, thank you!
