### ISSUE TITLE
dbNSFP dumper not working correctly

### ISSUE THREAD

**Issue by kevinxin90** [biothings/myvariant.info#97]
Issue:

The dumper only checks for release name.

In the case of dbNSFP, the provider has a minor update on the data source, but doesn't change the release name. So the dbNSFP dumper doesn't catch it.

Solution:

When checking release for dbNSFP, should both look for release name change as well as release date change.

**Comment by newgene** [comment]
new dbNSFP v4.1 is out. The dumper captured the new version, processed the data properly.
