### ISSUE TITLE
dbNSFP hgvsc and hgvsp

### ISSUE THREAD

**Issue by kevinxin90** [biothings/myvariant.info#98]
We currently merge hgvs ids from dbNSFP (which they get from SNPEFF, ANNOVAR, VEP) into one field. Might consider to separate them based on the source database.

**Comment by erikyao** [comment]
Currently we have json structures as:

```python
{
    "_id": hgvs_id,
    "dbnsfp": {
         "hgvsc": list(set(df["HGVSc_ANNOVAR"].split(';') + df["HGVSc_snpEff"].split(';') + df["HGVSc_VEP"].split(';'))),            
         "hgvsp": list(set(df["HGVSp_ANNOVAR"].split(';') + df["HGVSp_snpEff"].split(';') + df["HGVSp_VEP"].split(';'))),
    }
}
```

I think Kevin suggested the following structure:

```python
{
    "_id": hgvs_id,
    "dbnsfp": {
         "hgvsc": {
              "ANNOVAR": list(set(df["HGVSc_ANNOVAR"].split(';'))),
              "snpEff": list(set(df["HGVSc_snpEff"].split(';'))),
              "VEP": list(set(df["HGVSc_VEP"].split(';')))
         },            
         "hgvsp": {
              "ANNOVAR": list(set(df["HGVSp_ANNOVAR"].split(';'))),
              "snpEff": list(set(df["HGVSp_snpEff"].split(';'))),
              "VEP": list(set(df["HGVSp_VpEP"].split(';')))
         },          
    }
}
```

The IDs might be highly duplicated when parsed from `HGVSc_*` and `HGVSp_*` columns. To take a look into the real data, use the following code:

```python
import pandas as pd

df = pd.read_csv("datasources/dbnsfp/4.2a/dbNSFP4.2a_variant.chr18", sep="\t", na_values=["."], keep_default_na=True)
hgvsc_cols = ["HGVSc_ANNOVAR", "HGVSc_snpEff", "HGVSc_VEP"]
df[~df["HGVSc_ANNOVAR"].isnull()][hgvsc_cols].head()
```

|index|HGVSc_ANNOVAR              |HGVSc_snpEff               |HGVSc_VEP                  |
|-----|:-------------------------:|:-------------------------:|:-------------------------:|
|3151 |c.1A>C;c.1A>C;c.1A>C;c.1A>C|c.1A>C;c.1A>C;c.1A>C;c.1A>C|c.1A>C;c.1A>C;c.1A>C;c.1A>C|
|3152 |c.1A>G;c.1A>G;c.1A>G;c.1A>G|c.1A>G;c.1A>G;c.1A>G;c.1A>G|c.1A>G;c.1A>G;c.1A>G;c.1A>G|
|3153 |c.1A>T;c.1A>T;c.1A>T;c.1A>T|c.1A>T;c.1A>T;c.1A>T;c.1A>T|c.1A>T;c.1A>T;c.1A>T;c.1A>T|
|3154 |c.2T>A;c.2T>A;c.2T>A;c.2T>A|c.2T>A;c.2T>A;c.2T>A;c.2T>A|c.2T>A;c.2T>A;c.2T>A;c.2T>A|
|3155 |c.2T>C;c.2T>C;c.2T>C;c.2T>C|c.2T>C;c.2T>C;c.2T>C;c.2T>C|c.2T>C;c.2T>C;c.2T>C;c.2T>C|
