### ISSUE TITLE
Querymany randomly (?) failing

### ISSUE THREAD

**Issue by dborgesr** [biothings/myvariant.info#99]
Hello,

I am trying to iterate over a large number of variants using querymany in python.
With an input of ~10,000 variants in HGVS format using format_hgvs.

When I run my querymany commands it usually fails but at different number of variants, sometimes it gets through 3000, sometimes only 1000, and sometimes it even finishes and produces the expected and correct output.

Command run:
`                mv_var_hg19 = mv.querymany(cur_vars, 
                                           scopes=['_id','dbsnp.rsid'],  
                                           fields=["_id", 
                                                   "chrom", 
                                                   "hg19", 
                                                   "hg38",
                                                   "dbnsfp", 
                                                   "gnomad_genome", 
                                                   "dbnsfp", 
                                                   "dbsnp","cadd", 
                                                   "snpeff", 
                                                   "gnomad_genome"],
                                           species='human',
                                           assembly=assembly)`

The output from the error:
`~/miniconda3/lib/python3.6/site-packages/biothings_client/base.py in _querymany(self, qterms, scopes, **kwargs)
    535         li_query = []
    536         def query_fn(qterms): return self._querymany_inner(qterms, verbose=verbose, **kwargs)
--> 537         for hits in self._repeated_query(query_fn, qterms, verbose=verbose):
    538             if return_raw:
    539                 out.append(hits)   # hits is the raw response text

~/miniconda3/lib/python3.6/site-packages/biothings_client/base.py in _repeated_query(self, query_fn, query_li, verbose, **fn_kwargs)
    219                 print("querying {0}-{1}...".format(i + 1, cnt), end="")
    220             i = cnt
--> 221             from_cache, query_result = query_fn(batch, **fn_kwargs)
    222             yield query_result
    223             if verbose:

~/miniconda3/lib/python3.6/site-packages/biothings_client/base.py in query_fn(qterms)
    534         li_dup = []
    535         li_query = []
--> 536         def query_fn(qterms): return self._querymany_inner(qterms, verbose=verbose, **kwargs)
    537         for hits in self._repeated_query(query_fn, qterms, verbose=verbose):
    538             if return_raw:

~/miniconda3/lib/python3.6/site-packages/biothings_client/base.py in _querymany_inner(self, qterms, verbose, **kwargs)
    481         _kwargs.update(kwargs)
    482         _url = self.url + self._query_endpoint
--> 483         return self._post(_url, params=_kwargs, verbose=verbose)
    484 
    485     def _querymany(self, qterms, scopes=None, **kwargs):

~/miniconda3/lib/python3.6/site-packages/biothings_client/base.py in _post(self, url, params, verbose)
    175         if self.raise_for_status:
    176             # raise requests.exceptions.HTTPError if not 200
--> 177             res.raise_for_status()
    178         if return_raw:
    179             return from_cache, res

~/miniconda3/lib/python3.6/site-packages/requests/models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 500 Server Error: Internal Server Error for url: http://myvariant.info/v1/query/`

Any idea what's going on?

**Comment by kevinxin90** [comment]
@dborgesr 

Thanks for spotting the issue. The issue is caused because you're making some very data-intensive queries to the MyVariant.info server in a very short frame and the server throttled. 

While we're working on solutions to this issue,  I would like to recommend you try an alternative solution in the meantime, which is to break your large query into smaller chunks, e.g. 200 at a time.

```
mv_var_hg19 = []
for i in range(0, len(cur_var), 200):
    chunk = cur_var[i:i + 200]
    tmp = mv.querymany(chunk,
                       scopes=["_id"],
                       fields=["_id", "chrom", "hg19", "hg38", "dbnsfp", 
                                 "gnomad_genome", "dbsnp","cadd", "snpeff"],
                        species='human',
                       assembly='hg19')
    mv_var_hg19 += tmp
```
In this way, you can process a large amount of variants without throttling the system.

**Comment by dborgesr** [comment]
Ah cool! 

And sorry! I'll play a bit nicer from now on :)

I'm here to break your things after all.

--Thanks

**Comment by kevinxin90** [comment]
@dborgesr Our developed @namespacestd0 has optimized our AWS instances so that it could handle large POST calls elegantly (without the need to do truncations). Feel free to try it out.
